import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { notFound } from "next/navigation";
import { PageShell } from "@/components/ui";
import { getNewsById } from "@/lib/data";

export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const n=await getNewsById(id);return {title:n.title,description:n.summary,openGraph:{title:n.title,description:n.summary,images:n.image?[n.image]:[]}}}
export default async function Detail({params}:{params:Promise<{id:string}>}){const {id}=await params;if(!id)notFound();const n=await getNewsById(id);const paragraphs=n.content?.split(/\r?\n+/).map(p=>p.trim()).filter(Boolean)??[];return <PageShell><article><div className="wrap detail-hero"><Link className="article-back" href="/noticias"><ArrowLeft size={16}/> Todas as notícias</Link><div className="detail-meta"><span className="tag">{n.category}</span><span>{n.source} · {n.date}</span></div><h1>{n.title}</h1><p className="detail-subtitle">{n.summary}</p>{n.image&&<div className="detail-image" style={{backgroundImage:`url(${JSON.stringify(n.image)})`}}/>}</div><div className="wrap article">{paragraphs.length>0&&<section className="article-content"><h2>A notícia</h2>{paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>)}{n.sourceUrl&&<a className="source-link" href={n.sourceUrl} target="_blank" rel="noopener noreferrer">Ler publicação original em {n.source} <ExternalLink size={14}/></a>}</section>}<section className="capivara-explains"><div className="explain-heading"><small>CAPIVARA EXPLICA ✨</small><h2>Os principais pontos, sem complicação</h2>{n.summaryAI&&<p>{n.summaryAI}</p>}</div>{n.explain?.length?<div className="explain-list">{n.explain.map((item,index)=><div className="explain-item" key={`${item.position}-${item.title}`}><span>{index+1}</span><div><h3>{item.title}</h3><p>{item.description}</p></div></div>)}</div>:<div className="explain"><h3>O que aconteceu</h3><p>{n.summaryAI||n.summary}</p></div>}</section><nav className="article-next"><div><small>CONTINUE NO CAPIVARA WEB</small><h2>Mais notícias, mais contexto.</h2><p>Acompanhe as últimas atualizações diretamente pelo navegador, em qualquer dispositivo.</p></div><Link className="button" href="/noticias">Ver últimas notícias</Link></nav></div></article></PageShell>}
