"use client";
import Link from "next/link";
import { Clock,Download,ExternalLink,Share2,Sparkles,X } from "lucide-react";
import { useCallback,useEffect,useRef,useState } from "react";
import type { DailySummaryResponse,DailySummarySlide } from "@/lib/daily-summary";

const VIEWED_KEY="capivara-daily-summary-viewed";
const track=(event:string,params:Record<string,string|number|undefined>)=>window.gtag?.("event",event,params);
const dateLabel=(date:string)=>{const parsed=new Date(`${date}T12:00:00`);return Number.isNaN(parsed.valueOf())?date:new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"long",year:"numeric"}).format(parsed)};

function SummaryImage({slide}:{slide:DailySummarySlide}){const [failed,setFailed]=useState(false);if(!slide.imageUrl||failed)return <div className="daily-image-placeholder"><span>●</span> capivara</div>;return <div className="daily-news-image" style={{backgroundImage:`url(${JSON.stringify(slide.imageUrl)})`}} role="img" aria-label="Imagem da notícia" onError={()=>setFailed(true)}><img src={slide.imageUrl} alt="" onError={()=>setFailed(true)}/></div>}

function wrapText(context:CanvasRenderingContext2D,text:string,x:number,y:number,maxWidth:number,lineHeight:number,maxLines:number){const words=text.split(/\s+/);let line="",lineIndex=0;for(const word of words){const next=line?`${line} ${word}`:word;if(context.measureText(next).width>maxWidth&&line){context.fillText(line,x,y+lineIndex*lineHeight);line=word;lineIndex++;if(lineIndex===maxLines-1)break}else line=next}if(lineIndex<maxLines){const remaining=lineIndex===maxLines-1&&words.length>0?`${line.replace(/[.,;:]?$/,"…")}`:line;context.fillText(remaining,x,y+lineIndex*lineHeight)}}

async function createShareImage(summary:DailySummaryResponse){const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1920;const context=canvas.getContext("2d");if(!context)throw new Error("canvas");const gradient=context.createLinearGradient(0,0,1080,1920);gradient.addColorStop(0,"#221039");gradient.addColorStop(.42,"#071018");gradient.addColorStop(1,"#0b1a28");context.fillStyle=gradient;context.fillRect(0,0,1080,1920);context.fillStyle="#a855f7";context.beginPath();context.arc(104,120,16,0,Math.PI*2);context.fill();context.fillStyle="#fff";context.font="900 62px Arial";context.fillText("capivara",140,142);context.fillStyle="#cb8cff";context.font="900 30px Arial";context.fillText("CAPIVARA HOJE",74,285);context.fillStyle="#fff";context.font="700 62px Arial";context.fillText("O dia em poucos minutos",74,370);context.fillStyle="#98a6b4";context.font="32px Arial";context.fillText(dateLabel(summary.date),74,430);let y=565;const news=summary.slides.filter(slide=>slide.type==="NEWS").slice(0,4);news.forEach((slide,index)=>{context.fillStyle=index%2===0?"#8b35ee":"#247cc1";context.fillRect(74,y-42,10,225);context.fillStyle="#c88cff";context.font="900 24px Arial";context.fillText([slide.category,slide.sourceName].filter(Boolean).join(" · ").toUpperCase(),112,y);context.fillStyle="#f7f7fb";context.font="700 40px Arial";wrapText(context,slide.title,112,y+58,850,49,3);y+=270});context.fillStyle="#98a6b4";context.font="28px Arial";context.fillText("Entenda antes de opinar.",74,1740);context.fillStyle="#fff";context.font="700 32px Arial";context.fillText("usecapivara.com.br",74,1800);return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("blob")),"image/png"))}

export function DailySummary({summary}:{summary:DailySummaryResponse}){
  const [isNew,setIsNew]=useState(false);const [open,setOpen]=useState(false);const [index,setIndex]=useState(0);const [progress,setProgress]=useState(0);const [paused,setPaused]=useState(false);const [pageHidden,setPageHidden]=useState(false);const [reducedMotion,setReducedMotion]=useState(false);const [sharing,setSharing]=useState(false);const triggerRef=useRef<HTMLButtonElement>(null);const closeRef=useRef<HTMLButtonElement>(null);const progressRef=useRef(0);const pointerRef=useRef<{x:number;y:number;time:number}|null>(null);const slide=summary.slides[index];
  const close=useCallback(()=>{setOpen(false);setIndex(0);setProgress(0);progressRef.current=0;requestAnimationFrame(()=>triggerRef.current?.focus())},[]);
  const go=useCallback((next:number)=>{const target=Math.max(0,Math.min(summary.slides.length-1,next));setIndex(target);setProgress(0);progressRef.current=0},[summary.slides.length]);
  useEffect(()=>{setIsNew(window.localStorage.getItem(VIEWED_KEY)!==summary.date);track("daily_summary_card_viewed",{summary_date:summary.date})},[summary.date]);
  useEffect(()=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)");const update=()=>setReducedMotion(media.matches);update();media.addEventListener("change",update);const visibility=()=>setPageHidden(document.hidden);document.addEventListener("visibilitychange",visibility);return()=>{media.removeEventListener("change",update);document.removeEventListener("visibilitychange",visibility)}},[]);
  useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";closeRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")close();if(event.key==="ArrowRight")go(index+1);if(event.key==="ArrowLeft")go(index-1)};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",key)}},[close,go,index,open]);
  useEffect(()=>{if(!open||!slide)return;track("daily_summary_slide_viewed",{summary_date:summary.date,slide_type:slide.type.toLowerCase(),slide_index:index,feed_id:slide.feedId??undefined,category:slide.category??undefined,source_name:slide.sourceName??undefined})},[index,open,slide,summary.date]);
  useEffect(()=>{if(!open||paused||pageHidden||reducedMotion||!slide||slide.type==="FINISH")return;const timer=window.setInterval(()=>{progressRef.current+=50/7000;if(progressRef.current>=1){window.clearInterval(timer);go(index+1)}else setProgress(progressRef.current)},50);return()=>window.clearInterval(timer)},[go,index,open,pageHidden,paused,reducedMotion,slide]);
  function show(){window.localStorage.setItem(VIEWED_KEY,summary.date);setIsNew(false);setOpen(true);setIndex(0);track("daily_summary_opened",{summary_date:summary.date})}
  function pointerDown(event:React.PointerEvent){if((event.target as HTMLElement).closest("button,a"))return;pointerRef.current={x:event.clientX,y:event.clientY,time:Date.now()};setPaused(true)}
  function pointerUp(event:React.PointerEvent){const start=pointerRef.current;pointerRef.current=null;setPaused(false);if(!start||(event.target as HTMLElement).closest("button,a"))return;const dy=event.clientY-start.y;if(dy>90&&Math.abs(dy)>Math.abs(event.clientX-start.x)){close();return}if(Date.now()-start.time>350||Math.abs(dy)>20)return;const bounds=event.currentTarget.getBoundingClientRect();go(event.clientX<bounds.left+bounds.width/2?index-1:index+1)}
  async function share(){if(sharing)return;setSharing(true);try{const blob=await createShareImage(summary);const file=new File([blob],`capivara-hoje-${summary.date}.png`,{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:"Capivara Hoje"});track("daily_summary_shared",{summary_date:summary.date})}else{const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=file.name;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);try{await navigator.clipboard?.writeText(`Capivara Hoje — as principais notícias do dia: ${window.location.origin}`)}catch{}track("daily_summary_share_downloaded",{summary_date:summary.date})}}finally{setSharing(false)}}
  return <><section className="wrap daily-summary-card"><div className="daily-card-mark"><Sparkles size={25}/></div><div><span>{isNew&&<b>NOVO</b>} CAPIVARA HOJE</span><h2>As principais notícias do dia em poucos minutos</h2><p>{summary.estimatedReadingMinutes?`${summary.estimatedReadingMinutes} min de leitura · `:""}{dateLabel(summary.date)}</p></div><button ref={triggerRef} type="button" onClick={show}>Ver resumo <ExternalLink size={16}/></button></section>{open&&slide&&<div className="daily-overlay"><div className="daily-viewer" role="dialog" aria-modal="true" aria-label="Capivara Hoje" onPointerDown={pointerDown} onPointerUp={pointerUp} onPointerCancel={()=>{pointerRef.current=null;setPaused(false)}}><div className="daily-progress" aria-label={`Slide ${index+1} de ${summary.slides.length}`}>{summary.slides.map((_,position)=><span key={position}><i style={{width:`${position<index?100:position===index?progress*100:0}%`}}/></span>)}</div><button ref={closeRef} className="daily-close" type="button" onClick={close} aria-label="Fechar resumo"><X size={21}/></button><div className={`daily-slide daily-${slide.type.toLowerCase()}`}>
    {slide.type==="COVER"&&<div className="daily-cover-content"><div className="daily-brand"><span>●</span> capivara</div><span className="daily-eyebrow">CAPIVARA HOJE</span><h2>{slide.title}</h2><p>{slide.description}</p><div className="daily-cover-meta"><span>{dateLabel(summary.date)}</span>{summary.estimatedReadingMinutes&&<span><Clock size={15}/>{summary.estimatedReadingMinutes} min</span>}</div></div>}
    {slide.type==="NEWS"&&<><SummaryImage slide={slide}/><div className="daily-news-copy"><div className="daily-news-tags">{slide.category&&<span>{slide.category}</span>}{slide.impactLevel&&<span>Impacto {slide.impactLevel.toLowerCase()}</span>}</div><h2>{slide.title}</h2><p>{slide.description}</p>{slide.sourceName&&<small>Fonte: {slide.sourceName}</small>}{slide.candidates.length>0&&<div className="daily-candidates">{slide.candidates.map(candidate=><span key={candidate.id}>{candidate.name} · {candidate.party}</span>)}</div>}{slide.feedId&&<Link href={`/noticias/${slide.feedId}`} onClick={()=>track("daily_summary_news_opened",{summary_date:summary.date,slide_index:index,feed_id:slide.feedId??undefined,category:slide.category??undefined,source_name:slide.sourceName??undefined})}>Ler notícia completa <ExternalLink size={16}/></Link>}</div></>}
    {slide.type==="FINISH"&&<div className="daily-finish-content"><div className="daily-brand"><span>●</span> capivara</div><Sparkles size={34}/><h2>{slide.title}</h2><p>{slide.description}</p><Link href="/noticias">Voltar às notícias</Link><button type="button" onClick={share} disabled={sharing}><Share2 size={17}/>{sharing?"Preparando imagem…":"Compartilhar resumo"}</button><small><Download size={13}/> Caso o compartilhamento não esteja disponível, a imagem será baixada.</small></div>}
  </div><div className="daily-hint">Toque nos lados para navegar · segure para pausar</div></div></div>}</>
}
