"use client";

import { Share2,ThumbsDown,ThumbsUp } from "lucide-react";
import { useEffect,useState } from "react";
import { AnonymousSessionError } from "@/lib/anonymous-session";
import { FeedReactionError,getFeedReactions,reactionOperation,removeFeedReaction,setFeedReaction,type FeedReactionResponse,type ReactionType } from "@/lib/feed-reactions-api";

type State=FeedReactionResponse&{loading:boolean;submitting:boolean;error:string|null};
const empty=(feedId:number):State=>({feedId,likes:0,dislikes:0,myReaction:null,loading:true,submitting:false,error:null});
const track=(event:string,params:Record<string,string|number>)=>window.gtag?.("event",event,params);
const statusOf=(error:unknown)=>error instanceof FeedReactionError||error instanceof AnonymousSessionError?error.status:0;
const messageOf=(error:unknown)=>error instanceof AnonymousSessionError?error.message:error instanceof FeedReactionError&&error.status===429?"Muitas tentativas. Tente novamente mais tarde.":"Não foi possível atualizar sua reação.";
async function copy(url:string){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(url);const input=document.createElement("textarea");input.value=url;input.style.position="fixed";input.style.opacity="0";document.body.appendChild(input);input.select();const copied=document.execCommand("copy");input.remove();if(!copied)throw new Error("copy failed")}

export function FeedCardActions({feedId,title}:{feedId:number;title:string}){
  const [state,setState]=useState(()=>empty(feedId));const [retry,setRetry]=useState<ReactionType|null>(null);const [shareStatus,setShareStatus]=useState<string|null>(null);
  async function load(){setState(current=>({...current,loading:true,error:null}));try{const data=await getFeedReactions(feedId);setState({...data,loading:false,submitting:false,error:null})}catch(error){setState(current=>({...current,loading:false,error:"Não foi possível carregar as avaliações."}));track("news_reaction_error",{feed_id:feedId,http_status:statusOf(error),placement:"feed_card"})}}
  useEffect(()=>{void load()},[feedId]);
  async function react(selected:ReactionType){if(state.loading||state.submitting)return;const previous=state;setRetry(null);setState(current=>({...current,submitting:true,error:null}));try{const operation=reactionOperation(previous.myReaction,selected);const data=operation==="REMOVE"?await removeFeedReaction(feedId):await setFeedReaction(feedId,selected);setState({...data,loading:false,submitting:false,error:null});track(operation==="REMOVE"?"news_reaction_removed":selected==="LIKE"?"news_reaction_like":"news_reaction_dislike",{feed_id:feedId,reaction_type:selected.toLowerCase(),placement:"feed_card"})}catch(error){setState({...previous,submitting:false,error:messageOf(error)});setRetry(selected);track("news_reaction_error",{feed_id:feedId,reaction_type:selected.toLowerCase(),http_status:statusOf(error),placement:"feed_card"})}}
  async function share(){const url=`${window.location.origin}/noticias/${feedId}`;const nativeShare=typeof navigator.share==="function";setShareStatus(null);try{if(nativeShare)await navigator.share({title,text:`${title} — Capivara`,url});else{await copy(url);setShareStatus("Link copiado")};track("news_card_shared",{feed_id:feedId,share_method:nativeShare?"native":"clipboard"})}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;setShareStatus("Não foi possível compartilhar");track("news_card_share_error",{feed_id:feedId})}}
  const busy=state.loading||state.submitting;
  return <div className="feed-card-footer"><div className="feed-card-actions" aria-label="Avalie sua experiência com esta notícia"><button type="button" className={state.myReaction==="LIKE"?"selected":""} aria-pressed={state.myReaction==="LIKE"} aria-label={`Gostei da experiência de leitura desta notícia. ${state.likes} avaliações`} title="Gostei da experiência com esta notícia" disabled={busy} onClick={()=>react("LIKE")}><ThumbsUp size={17}/><span>{state.loading?"—":state.likes}</span>{state.myReaction==="LIKE"&&<i>Selecionado</i>}</button><button type="button" className={state.myReaction==="DISLIKE"?"selected":""} aria-pressed={state.myReaction==="DISLIKE"} aria-label={`Não gostei da experiência de leitura desta notícia. ${state.dislikes} avaliações`} title="Não gostei da experiência com esta notícia" disabled={busy} onClick={()=>react("DISLIKE")}><ThumbsDown size={17}/><span>{state.loading?"—":state.dislikes}</span>{state.myReaction==="DISLIKE"&&<i>Selecionado</i>}</button><button type="button" aria-label="Compartilhar esta notícia" title="Compartilhar notícia" onClick={share}><Share2 size={17}/><span className="action-text">Compartilhar</span></button></div>{(state.error||shareStatus)&&<div className={`feed-card-feedback ${state.error?"error":""}`} role="status"><span>{state.error||shareStatus}</span>{state.error&&<button type="button" onClick={()=>retry?react(retry):load()}>Tentar novamente</button>}</div>}</div>
}
