"use client";
import { useEffect,useRef,useState } from "react";
import { Bot,HelpCircle,RefreshCw,Users,X } from "lucide-react";
import { askFeedQuestion,FeedQuestionError,feedQuestionErrorMessage,type FeedQuestionResponse,type FeedQuestionType } from "@/lib/feed-questions";

type FeedQuestionState={status:"idle"}|{status:"loading";questionType:FeedQuestionType}|{status:"success";data:FeedQuestionResponse}|{status:"error";message:string;questionType:FeedQuestionType};
const analyticsName=(type:FeedQuestionType)=>type==="EXPLAIN_NEWS"?"explain_news":"people_mentioned";
const track=(name:string,params?:Record<string,string>)=>{if(typeof window!=="undefined")(window as Window&{gtag?:(...args:unknown[])=>void}).gtag?.("event",name,params)};

export function NewsQuestionPanel({feedId}:{feedId:number}){
  const [open,setOpen]=useState(false);const [state,setState]=useState<FeedQuestionState>({status:"idle"});const dialogRef=useRef<HTMLDivElement>(null);const triggerRef=useRef<HTMLButtonElement>(null);const closeRef=useRef<HTMLButtonElement>(null);
  function show(){setState({status:"idle"});setOpen(true);track("news_question_opened")}
  function close(){setOpen(false);setState({status:"idle"});requestAnimationFrame(()=>triggerRef.current?.focus())}
  async function ask(questionType:FeedQuestionType){if(state.status==="loading")return;setState({status:"loading",questionType});track("news_question_asked",{question_type:analyticsName(questionType)});try{setState({status:"success",data:await askFeedQuestion(feedId,questionType)})}catch(error){const status=error instanceof FeedQuestionError?error.status:-1;setState({status:"error",message:feedQuestionErrorMessage(status),questionType})}}
  useEffect(()=>{if(!open)return;const previousOverflow=document.body.style.overflow;document.body.style.overflow="hidden";closeRef.current?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){close();return}if(event.key!=="Tab"||!dialogRef.current)return;const focusable=[...dialogRef.current.querySelectorAll<HTMLElement>('button,[href],[tabindex]:not([tabindex="-1"])')].filter(item=>!item.hasAttribute("disabled"));if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=previousOverflow;document.removeEventListener("keydown",onKey)}},[open]);
  return <><button ref={triggerRef} className="news-question-float" type="button" onClick={show} aria-haspopup="dialog"><HelpCircle size={19}/> Tirar uma dúvida</button>{open&&<div className="news-question-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div ref={dialogRef} className="news-question-dialog" role="dialog" aria-modal="true" aria-labelledby="news-question-title"><div className="news-question-head"><div><span>DÚVIDAS COM IA</span><h2 id="news-question-title">Como podemos ajudar?</h2><p>Escolha uma dúvida sobre esta notícia.</p></div><button ref={closeRef} type="button" onClick={close} aria-label="Fechar"><X size={21}/></button></div><div className="news-question-body">
    {state.status==="idle"&&<div className="news-question-options"><button type="button" onClick={()=>ask("EXPLAIN_NEWS")}><span><Bot size={22}/></span><div><strong>Me explica melhor esta notícia</strong><p>Entenda o conteúdo em uma linguagem mais simples.</p></div></button><button type="button" onClick={()=>ask("PEOPLE_MENTIONED")}><span><Users size={22}/></span><div><strong>Quem são as pessoas citadas?</strong><p>Veja quem são e qual o papel delas nesta notícia.</p></div></button></div>}
    {state.status==="loading"&&<div className="news-question-loading" aria-live="polite"><span className="ai-loader"/><h3>Analisando a notícia…</h3><p>Isso pode levar alguns segundos.</p></div>}
    {state.status==="success"&&<div className="news-question-result"><span className="result-type">RESPOSTA</span><h3>{state.data.title}</h3>{state.data.questionType==="EXPLAIN_NEWS"?<p className="news-answer">{state.data.answer||"Não foi possível gerar uma explicação para esta notícia."}</p>:state.data.people.length?<div className="people-list">{state.data.people.map((person,index)=><article key={`${person.name}-${index}`}><h4>{person.name}</h4><p>{person.description}</p><div><strong>Papel nesta notícia</strong><span>{person.roleInNews}</span></div></article>)}</div>:<p className="news-answer">Nenhuma pessoa pôde ser identificada com segurança nesta notícia.</p>}<small>Resposta gerada por IA com base no conteúdo da notícia.</small><button className="question-secondary" type="button" onClick={()=>setState({status:"idle"})}>Fazer outra pergunta</button></div>}
    {state.status==="error"&&<div className="news-question-error" role="alert"><HelpCircle size={29}/><h3>Não conseguimos concluir</h3><p>{state.message}</p><div><button type="button" onClick={()=>ask(state.questionType)}><RefreshCw size={16}/> Tentar novamente</button><button className="question-secondary" type="button" onClick={()=>setState({status:"idle"})}>Escolher outra pergunta</button></div></div>}
  </div></div></div>}</>
}
