"use client";
import { useEffect,useMemo,useState } from "react";
import type { News,NewsPage } from "@/lib/data";
import { NewsCard } from "./ui";

const norm=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();

export function NewsFilter({initialPage}:{initialPage:NewsPage}){
  const [news,setNews]=useState<News[]>(initialPage.items);const [cursor,setCursor]=useState(initialPage.nextCursor);const [hasMore,setHasMore]=useState(initialPage.hasMore);const [unavailable,setUnavailable]=useState(Boolean(initialPage.unavailable));const [loading,setLoading]=useState(false);const [loadError,setLoadError]=useState(false);const [active,setActive]=useState("Todas");
  const ordered=useMemo(()=>[...news].sort((a,b)=>(b.publishedAt?Date.parse(b.publishedAt):0)-(a.publishedAt?Date.parse(a.publishedAt):0)||Number(b.id)-Number(a.id)),[news]);
  const categories=useMemo(()=>["Todas",...Array.from(new Set(ordered.map(item=>item.category).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"pt-BR"))],[ordered]);
  const visible=useMemo(()=>active==="Todas"?ordered:ordered.filter(item=>norm(item.category)===norm(active)),[active,ordered]);
  useEffect(()=>{const controller=new AbortController();fetch("/api/feed",{cache:"no-store",signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<NewsPage>}).then(page=>{if(page.unavailable)throw new Error();setNews(page.items);setCursor(page.nextCursor);setHasMore(page.hasMore);setUnavailable(false)}).catch(error=>{if(error?.name!=="AbortError"&&news.length===0)setUnavailable(true)});return()=>controller.abort()},[]);
  async function loadMore(){if(!cursor||loading)return;setLoading(true);setLoadError(false);try{const response=await fetch(`/api/feed?cursor=${encodeURIComponent(cursor)}`,{cache:"no-store"});if(!response.ok)throw new Error();const page=await response.json() as NewsPage;if(page.unavailable)throw new Error();setNews(current=>[...current,...page.items.filter(item=>!current.some(existing=>existing.id===item.id))]);setCursor(page.nextCursor);setHasMore(page.hasMore)}catch{setLoadError(true)}finally{setLoading(false)}}
  if(unavailable&&!news.length)return <div className="empty-state news-unavailable"><h3>Não foi possível atualizar as notícias agora.</h3><p>Tente recarregar a página em alguns instantes. Não exibimos notícias antigas como se fossem atuais.</p><button className="load-more" type="button" onClick={()=>window.location.reload()}>Tentar novamente</button></div>;
  return <div className="filter-panel"><div className="filters" aria-label="Filtrar notícias por categoria">{categories.map(option=>{const count=option==="Todas"?news.length:news.filter(item=>norm(item.category)===norm(option)).length;return <button type="button" className={`filter ${active===option?"active":""}`} onClick={()=>setActive(option)} aria-pressed={active===option} key={option}>{option} <span>{count}</span></button>})}</div><div className="results-count">{visible.length} {visible.length===1?"notícia":"notícias"}</div><div className="list">{visible.map(item=><NewsCard item={item} key={item.id}/>)}{!visible.length&&<div className="empty-state"><h3>Nenhuma notícia nesta categoria.</h3><p>Tente selecionar outro assunto.</p></div>}</div>{loadError&&<p className="feed-load-error">Não foi possível carregar mais notícias. Tente novamente.</p>}{hasMore&&<button className="load-more" type="button" onClick={loadMore} disabled={loading}>{loading?"Carregando…":loadError?"Tentar novamente":"Carregar mais notícias"}</button>}</div>
}
