"use client";
import { ThumbsDown,ThumbsUp } from "lucide-react";
import { useEffect,useState } from "react";
import { AnonymousSessionError } from "@/lib/anonymous-session";
import { FeedReactionError,getFeedReactions,reactionOperation,removeFeedReaction,setFeedReaction,type FeedReactionResponse,type ReactionType } from "@/lib/feed-reactions-api";

type ReactionState={likes:number;dislikes:number;myReaction:ReactionType|null;status:"idle"|"loading"|"submitting"|"success"|"error";errorMessage:string|null};
const initialState:ReactionState={likes:0,dislikes:0,myReaction:null,status:"loading",errorMessage:null};
const track=(event:string,params:Record<string,string|number>)=>window.gtag?.("event",event,params);
const friendlyError=(error:unknown)=>error instanceof AnonymousSessionError?error.message:error instanceof FeedReactionError?(error.status===429?"Não foi possível iniciar sua participação agora. Tente novamente mais tarde.":error.message):"Não foi possível atualizar sua reação. Tente novamente.";
const statusOf=(error:unknown)=>error instanceof FeedReactionError||error instanceof AnonymousSessionError?error.status:0;

export function NewsReactions({feedId}:{feedId:number}){
  const [state,setState]=useState<ReactionState>(initialState);const [hasLoaded,setHasLoaded]=useState(false);
  async function load(){setState(current=>({...current,status:"loading",errorMessage:null}));try{const data=await getFeedReactions(feedId);apply(data,"success")}catch(error){setState(current=>({...current,status:"error",errorMessage:"Não foi possível carregar as reações agora."}));track("news_reaction_error",{feed_id:feedId,http_status:statusOf(error)})}}
  function apply(data:FeedReactionResponse,status:ReactionState["status"]){setHasLoaded(true);setState({likes:data.likes,dislikes:data.dislikes,myReaction:data.myReaction,status,errorMessage:null})}
  useEffect(()=>{void load()},[feedId]);
  async function react(selected:ReactionType){if(state.status==="submitting"||state.status==="loading")return;const previous=state;setState(current=>({...current,status:"submitting",errorMessage:null}));try{const operation=reactionOperation(previous.myReaction,selected);const data=operation==="REMOVE"?await removeFeedReaction(feedId):await setFeedReaction(feedId,selected);apply(data,"success");track(operation==="REMOVE"?"news_reaction_removed":selected==="LIKE"?"news_reaction_like":"news_reaction_dislike",{feed_id:feedId,reaction_type:selected.toLowerCase()})}catch(error){setState({...previous,status:"error",errorMessage:friendlyError(error)});track("news_reaction_error",{feed_id:feedId,reaction_type:selected.toLowerCase(),http_status:statusOf(error)})}}
  const loading=state.status==="loading";const submitting=state.status==="submitting";
  if(!loading&&!hasLoaded)return <section className="news-reactions" aria-labelledby="news-reactions-title"><div><span>REAÇÃO DOS LEITORES</span><h2 id="news-reactions-title">O que você achou desta notícia?</h2></div><div className="reaction-error" role="alert"><span>{state.errorMessage}</span><button type="button" onClick={load}>Tentar novamente</button></div></section>;
  return <section className="news-reactions" aria-labelledby="news-reactions-title"><div><span>REAÇÃO DOS LEITORES</span><h2 id="news-reactions-title">O que você achou desta notícia?</h2></div>{loading?<div className="reaction-skeleton" aria-label="Carregando reações"><i/><i/></div>:<div className="reaction-actions"><button type="button" className={state.myReaction==="LIKE"?"selected":""} aria-pressed={state.myReaction==="LIKE"} aria-label={`${state.myReaction==="LIKE"?"Remover curtida":"Curtir"}. ${state.likes} curtidas`} disabled={submitting} onClick={()=>react("LIKE")}><ThumbsUp size={20}/><strong>{state.likes}</strong>{state.myReaction==="LIKE"&&<small>Selecionado</small>}</button><button type="button" className={state.myReaction==="DISLIKE"?"selected":""} aria-pressed={state.myReaction==="DISLIKE"} aria-label={`${state.myReaction==="DISLIKE"?"Remover descurtida":"Descurtir"}. ${state.dislikes} descurtidas`} disabled={submitting} onClick={()=>react("DISLIKE")}><ThumbsDown size={20}/><strong>{state.dislikes}</strong>{state.myReaction==="DISLIKE"&&<small>Selecionado</small>}</button>{submitting&&<span className="reaction-updating"><i className="ai-loader"/> Atualizando…</span>}</div>}{state.errorMessage&&<div className="reaction-error" role="alert"><span>{state.errorMessage}</span>{state.status==="error"&&state.likes===0&&state.dislikes===0&&<button type="button" onClick={load}>Tentar novamente</button>}</div>}</section>
}
