"use client";
import { useRef,useState } from "react";
import { ArrowLeftRight,Bot,ChevronDown,Sparkles } from "lucide-react";
import type { Politician } from "@/lib/data";
import type { ProposalAnswer as Answer,ProposalComparison as Comparison,ProposalQuestion } from "@/lib/proposals";
import { PERCENTAGE_DISCLAIMER } from "@/lib/proposals";
import { ProposalAnswer } from "@/components/proposal-answer";

type SideState={loading:boolean;error?:string;answer?:Answer};type ThemeState={question:ProposalQuestion;a:SideState;b:SideState};
async function readJson(response:Response){const json=await response.json();if(!response.ok)throw new Error(json.error??"Não foi possível concluir a consulta.");return json}
const themeTerms:Record<string,string[]>={saúde:["saúde"],economia:["economia","emprego"],educação:["educação"],segurança:["segurança"],social:["social","habitação"],infraestrutura:["infraestrutura","meio ambiente"]};
const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const findQuestion=(theme:string,questions:ProposalQuestion[])=>{const key=Object.keys(themeTerms).find(item=>normalize(theme).includes(normalize(item)));const terms=key?themeTerms[key]:[theme];return questions.find(q=>terms.some(term=>normalize(q.title).includes(normalize(term))))};

export function ProposalComparison({candidates}:{candidates:Politician[]}){
  const [aId,setAId]=useState(candidates[0]?.id??"");const [bId,setBId]=useState(candidates[1]?.id??"");const [comparison,setComparison]=useState<Comparison>();const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [themes,setThemes]=useState<Record<string,ThemeState>>({});const questionsRef=useRef<ProposalQuestion[]|undefined>(undefined);const questionsPromise=useRef<Promise<ProposalQuestion[]>|undefined>(undefined);
  async function getQuestions(){if(questionsRef.current)return questionsRef.current;if(!questionsPromise.current)questionsPromise.current=fetch("/api/proposals/questions").then(readJson).then(json=>{questionsRef.current=json.questions;return json.questions});return questionsPromise.current}
  async function compare(){setLoading(true);setError("");setComparison(undefined);setThemes({});try{setComparison(await readJson(await fetch("/api/proposals/compare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({candidateAId:Number(aId),candidateBId:Number(bId)})})))}catch(err){setError(err instanceof Error?err.message:"Não foi possível comparar as propostas.")}finally{setLoading(false)}}
  async function askSide(theme:string,question:ProposalQuestion,side:"a"|"b",candidateId:number){setThemes(current=>({...current,[theme]:{...current[theme],[side]:{loading:true}}}));try{const answer=await readJson(await fetch("/api/proposals/ask",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({candidateId,questionId:question.id,question:question.question})}));setThemes(current=>({...current,[theme]:{...current[theme],[side]:{loading:false,answer}}}))}catch(err){setThemes(current=>({...current,[theme]:{...current[theme],[side]:{loading:false,error:err instanceof Error?err.message:"Não foi possível gerar a resposta."}}}))}}
  async function explain(theme:string){try{const question=findQuestion(theme,await getQuestions());if(!question)throw new Error("Ainda não há uma pergunta sugerida para este tema.");setThemes(current=>({...current,[theme]:{question,a:{loading:true},b:{loading:true}}}));void askSide(theme,question,"a",comparison!.candidateA.id);void askSide(theme,question,"b",comparison!.candidateB.id)}catch(err){const error=err instanceof Error?err.message:"Não foi possível carregar a pergunta.";setThemes(current=>({...current,[theme]:{question:{id:0,title:theme,question:"",position:0},a:{loading:false,error},b:{loading:false,error}}}))}}
  if(candidates.length<2)return <div className="compare-empty"><h2>Comparação indisponível</h2><p>Precisamos de pelo menos dois pré-candidatos à Presidência com propostas disponíveis.</p></div>;
  return <div className="compare-workspace"><section className="compare-controls"><div className="compare-select"><label htmlFor="candidate-a">Candidato A</label><div><select id="candidate-a" value={aId} onChange={event=>setAId(event.target.value)}>{candidates.map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.name} · {candidate.party}</option>)}</select><ChevronDown size={17}/></div><small>ID {aId||"—"}</small></div><ArrowLeftRight className="compare-swap" aria-hidden="true"/><div className="compare-select blue"><label htmlFor="candidate-b">Candidato B</label><div><select id="candidate-b" value={bId} onChange={event=>setBId(event.target.value)}>{candidates.map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.name} · {candidate.party}</option>)}</select><ChevronDown size={17}/></div><small>ID {bId||"—"}</small></div><button className="compare-button" type="button" disabled={loading||!aId||!bId||aId===bId} onClick={compare}>{loading?<><span className="ai-loader"/> Comparando…</>:<><Sparkles size={17}/> Comparar propostas</>}</button></section>
    {aId===bId&&<p className="compare-inline-error">Escolha dois candidatos diferentes.</p>}{error&&<div className="compare-error" role="alert"><p>{error}</p><button type="button" onClick={compare}>Tentar novamente</button></div>}{!comparison&&!loading&&!error&&<div className="compare-placeholder"><Bot size={28}/><h2>Escolha dois nomes para começar</h2><p>A comparação organiza a presença dos temas nos planos. Nenhuma análise é iniciada automaticamente.</p></div>}
    {comparison&&comparison.themes.length===0&&<div className="compare-empty"><h2>Sem propostas disponíveis</h2><p>A comparação ainda não possui temas suficientes para estes candidatos.</p></div>}
    {comparison&&<section className="comparison-result"><div className="comparison-names"><div><small>CANDIDATO A · ID {comparison.candidateA.id}</small><h2>{comparison.candidateA.name}</h2><span>{comparison.candidateA.party}{comparison.candidateA.number?` · ${comparison.candidateA.number}`:""}</span></div><div className="blue"><small>CANDIDATO B · ID {comparison.candidateB.id}</small><h2>{comparison.candidateB.name}</h2><span>{comparison.candidateB.party}{comparison.candidateB.number?` · ${comparison.candidateB.number}`:""}</span></div></div><p className="percentage-warning">{PERCENTAGE_DISCLAIMER}</p><div className="themes-list">{comparison.themes.map(item=>{const state=themes[item.theme];return <article className="theme-card" key={item.theme}><div className="theme-top"><h3>{item.theme}</h3><button type="button" onClick={()=>explain(item.theme)} disabled={Boolean(state?.a.loading||state?.b.loading)}>{state?<span>Atualizar explicação</span>:<span>Entender este tema</span>}</button></div><div className="theme-bars"><div className="theme-bar purple"><span style={{width:`${Math.max(0,Math.min(100,item.candidateAPercentage))}%`}}/><b>{item.candidateAPercentage}%</b></div><div className="theme-bar blue"><span style={{width:`${Math.max(0,Math.min(100,item.candidateBPercentage))}%`}}/><b>{item.candidateBPercentage}%</b></div></div>{state&&<div className="theme-explanations"><div><small>{comparison.candidateA.name}</small><ProposalAnswer tone="purple" answer={state.a.answer} error={state.a.error} loading={state.a.loading} onRetry={()=>askSide(item.theme,state.question,"a",comparison.candidateA.id)}/></div><div><small>{comparison.candidateB.name}</small><ProposalAnswer tone="blue" answer={state.b.answer} error={state.b.error} loading={state.b.loading} onRetry={()=>askSide(item.theme,state.question,"b",comparison.candidateB.id)}/></div></div>}</article>})}</div><div className="methodology"><strong>Como esta leitura foi feita</strong><p>{comparison.methodology}</p></div></section>}
  </div>
}
