import Link from "next/link";
import { ArrowRight, Bolt, Newspaper, Search, ShieldCheck, Sparkles, TrendingUp, Users } from "lucide-react";
import type { News, Politician } from "@/lib/data";

export function Logo(){return <Link className="logo" href="/"><span>●</span> capivara</Link>}
export function Header(){return <header><div className="nav wrap"><Logo/><nav><Link href="/noticias">Notícias</Link><Link href="/politicos">Políticos</Link><Link href="/em-alta">Em alta</Link><Link href="/sobre">Sobre</Link></nav><AppButton small/></div></header>}
export function Footer(){return <footer><div className="wrap footer-grid"><div><Logo/><p>Política explicada sem complicação.</p></div><div><b>Conteúdo</b><Link href="/noticias">Notícias</Link><Link href="/politicos">Políticos</Link><Link href="/em-alta">Em alta</Link></div><div><b>Transparência</b><Link href="/politica-editorial">Política editorial</Link><Link href="/uso-de-ia">Uso de IA</Link><Link href="/politica-de-privacidade">Privacidade</Link><Link href="/contato">Contato</Link></div></div><div className="wrap copyright">© 2026 Capivara. Informação para entender, não para confundir.</div></footer>}
export function AppButton({small=false}:{small?:boolean}){return <a className={`button ${small?'small':''}`} href={process.env.NEXT_PUBLIC_PLAY_STORE_URL || "#baixar"}>{small?"Baixar app":"Baixar na Google Play"}<ArrowRight size={17}/></a>}
export function PageShell({children}:{children:React.ReactNode}){return <><Header/><main>{children}</main><Footer/></>}
export function NewsCard({item,featured=false}:{item:News;featured?:boolean}){return <Link href={`/noticias/${item.id}`} className={`news-card ${featured?'featured':''}`}><div className="news-image" style={item.image?{backgroundImage:`linear-gradient(0deg,rgba(7,16,24,.8),transparent),url(${item.image})`}:undefined}/><div className="news-body"><span className="tag">{item.category}</span><h3>{item.title}</h3><p>{item.summary}</p><small>{item.source} · {item.date}</small></div></Link>}
export function Avatar({p}:{p:Politician}){return p.image?<span className="avatar photo" style={{backgroundImage:`url(${p.image})`}}/>:<span className={`avatar a-${p.id}`}>{p.initials}</span>}
export function PoliticianCard({p,rank}:{p:Politician;rank?:number}){return <Link href={`/politicos/${p.id}`} className="politician-card">{rank&&<strong className="rank">0{rank}</strong>}<Avatar p={p}/><div><h3>{p.name}</h3><p><span className="party">{p.party}</span> {p.number}</p><small>{p.role}</small></div>{p.growth&&<strong className="growth"><TrendingUp size={16}/> {p.growth}%</strong>}<ArrowRight className="chevron"/></Link>}
export function SectionTitle({eyebrow,title,link}:{eyebrow?:string;title:string;link?:string}){return <div className="section-title"><div>{eyebrow&&<span>{eyebrow}</span>}<h2>{title}</h2></div>{link&&<Link href={link}>Ver tudo <ArrowRight size={16}/></Link>}</div>}
export const featureIcons=[Sparkles,ShieldCheck,Bolt,Users,Newspaper,Search];
